comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true


codecov:
  token: "cb85780b-d33d-4b40-851a-cdf3df86a05c"
